### ISSUE TITLE
Specifying only one dimension of a grid when there aren't enough children to fill said dimension causes a segfault

### ISSUE THREAD

**Issue by illode** [terrastruct/d2#1188]
A [simple example](https://play.d2lang.com/?script=goeZlYIRLxcvV35eKhcgAAD__w%3D%3D):
```
grid-rows: 2

one
```

Happens in both the CLI version and the web version.

<details><summary>CLI output</summary>
<p>

```
❯ d2 pointer.d2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55e210b0688d]

goroutine 40 [running]:
oss.terrastruct.com/d2/d2exporter.toShape(_, _)
        /build/d2/src/d2/d2exporter/export.go:135 +0x16d
oss.terrastruct.com/d2/d2exporter.Export({0x55e211aa2bb8?, 0xc000832600?}, 0xc0001a40b0, 0x0)
        /build/d2/src/d2/d2exporter/export.go:31 +0x215
oss.terrastruct.com/d2/d2lib.compile({0x55e211aa2bb8, 0xc000832600}, 0xc0001a40b0, 0xc0008d6ce0)
        /build/d2/src/d2/d2lib/d2.go:94 +0x23c
oss.terrastruct.com/d2/d2lib.Compile({0x55e211aa2bb8, 0xc000832600}, {0xc00017b710, 0x14}, 0xd0?)
        /build/d2/src/d2/d2lib/d2.go:48 +0x10d
oss.terrastruct.com/d2/d2cli.compile({0x55e211aa2bb8, 0xc000832600}, 0xc00019ec40, {0x55e211aa4850?, 0x55e2122a61c0}, {0x64, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        /build/d2/src/d2/d2cli/main.go:326 +0x29e
oss.terrastruct.com/d2/d2cli.Run({0x55e211aa2b48?, 0xc0000e00a0?}, 0xc00019ec40)
        /build/d2/src/d2/d2cli/main.go:288 +0x213e
oss.terrastruct.com/util-go/xmain.(*State).Main.func1()
        /build/d2/src/pkg/mod/oss.terrastruct.com/util-go@v0.0.0-20230320053557-dcb5aac7d972/xmain/xmain.go:105 +0x71
created by oss.terrastruct.com/util-go/xmain.(*State).Main
        /build/d2/src/pkg/mod/oss.terrastruct.com/util-go@v0.0.0-20230320053557-dcb5aac7d972/xmain/xmain.go:103 +0x155
```
</p>
</details>

**Comment by alixander** [comment]
thank you @illode, can confirm, will be fixed asap
