### ISSUE TITLE
panic: outputting gif

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#1238]
t.d2
```
x
```
https://play.d2lang.com/?l=&script=quACBAAA__8%3D&

\>d2  --animate-interval=120 t.d2 t.gif
```
panic: runtime error: index out of range [255] with length 64

goroutine 20 [running]:
oss.terrastruct.com/d2/lib/xgif.AnimatePNGs(0xc000152c40, {0xc0006e8000, 0x1, 0x0?}, 0x78)
        oss.terrastruct.com/d2/lib/xgif/xgif.go:88 +0xbf6
oss.terrastruct.com/d2/d2cli.compile({0x27c5038, 0xc0007b2000}, 0xc000152c40, {0x27c6d80, 0x2ffb090}, {0x64, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        oss.terrastruct.com/d2/d2cli/main.go:366 +0xc31
oss.terrastruct.com/d2/d2cli.Run({0x27c4fc8?, 0xc000665900?}, 0xc000152c40)
        oss.terrastruct.com/d2/d2cli/main.go:297 +0x24f4
oss.terrastruct.com/util-go/xmain.(*State).Main.func1()
        oss.terrastruct.com/util-go@v0.0.0-20230320053557-dcb5aac7d972/xmain/xmain.go:105 +0x71
created by oss.terrastruct.com/util-go/xmain.(*State).Main
        oss.terrastruct.com/util-go@v0.0.0-20230320053557-dcb5aac7d972/xmain/xmain.go:103 +0x155
```

**Comment by gavin-ts** [comment]
may be related to #1206
