### ISSUE TITLE
feature: WASM web app

### ISSUE THREAD

**Issue by caner-cetin** [terrastruct/d2#136]
A web editor, for at least preview can be done with https://go-app.dev/. I may work on this, couldn't find anything similar on issues. pls hit me up if someone already works on a web app.

**Comment by nhooyr** [comment]
This is a goal. @alixander thoughts on doing it for the playground? That way we don't even need a stateful API, all static!!!

**Comment by alixander** [comment]
our wasm build currently is 50M lmao. the vast majority is Goja. the other big dead weight is playwright

<img width="368" alt="Screen Shot 2022-12-06 at 6 56 13 PM" src="https://user-images.githubusercontent.com/3120367/206076873-d3b41dfc-f789-4802-969e-73392ea2ecde.png">

**Comment by alixander** [comment]
even if we remove deadweight and optimize for wasm, realistically we're still looking at 20+ MB. that's a nonstarter for the fast load times desired of the playground

**Comment by alixander** [comment]
i did end up ripping out a lot of shit for tinygo, still no luck. 

<img width="907" alt="Screen Shot 2022-12-06 at 7 54 09 PM" src="https://user-images.githubusercontent.com/3120367/206084363-778b20ba-863c-45e7-8878-53a84f025b6c.png">

**Comment by alixander** [comment]
i suppose 20 MB with a 70% gzip compression isn't that terrible

**Comment by alixander** [comment]
without goja, playwright, elk, dagre, i got the build down to 27M, compressed with gzip is 6.5M. 

compressed with brotli is 4.4M. i think we can work with that. @nhooyr wdyt

**Comment by nhooyr** [comment]
Yea we don't need goja on the web, we can run the JS directly in the browser. See #366 

Sure, 4.4M is excellent.

**Comment by zachcp** [comment]
+1 for this.  Would love to have something like a fully embeddable playground/static site.

**Comment by alixander** [comment]
Thank you for the suggestion. I tried tinygo with some minimal effort ~a year ago but ran into errors. The size shouldn't be an issue anyway once we shed unused dependencies for wasm.

**Comment by caner-cetin** [comment]
i forgot why i asked for this feature and what is D2 but, gratz! and thank you :3

**Comment by alixander** [comment]
haha yeah this one's been on the backburner for a *while*

**Comment by nhooyr** [comment]
Slick! 🚀

**Comment by zachcp** [comment]
Awesome!

**Comment by F0rgenet** [comment]
Tried to build D2js WASM module using tinygo
```fish
forgenet@192 ~/P/t/p/d/d2js (master)> /usr/local/tinygo/bin/tinygo build -target=wasm
```
```js
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x91622c]

goroutine 899 [running]:
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc017d6c000, 0xc010693180, {0xc01a20cb90, 0x6, 0x0?}, 0xc007cb8b40, {0xc00611b2c0, 0x28})
        /__w/tinygo/tinygo/interp/interpreter.go:369 +0x408c
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc017d6c000, 0xc0107099f0, {0xc01a131110, 0x2, 0x0?}, 0xc007c60ed0, {0xc00611b110, 0x24})
        /__w/tinygo/tinygo/interp/interpreter.go:560 +0x81f7
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc017d6c000, 0xc0107080f0, {0xc01955fd10, 0x3, 0x0?}, 0xc007c32c90, {0xc01a9da5c0, 0x20})
        /__w/tinygo/tinygo/interp/interpreter.go:560 +0x81f7
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc017d6c000, 0xc01061de50, {0xc019487c10, 0x2, 0x0?}, 0xc007b02e70, {0xc01989bee0, 0x1c})
        /__w/tinygo/tinygo/interp/interpreter.go:560 +0x81f7
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc017d6c000, 0xc01b23fef0, {0xc018df8790, 0x2, 0x0?}, 0xc005ab2ab0, {0xc00e43e2d0, 0x18})
        /__w/tinygo/tinygo/interp/interpreter.go:560 +0x81f7
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc017d6c000, 0xc01b23fea0, {0xc018d98a90, 0x2, 0x0?}, 0xc007099560, {0xc00d136360, 0x14})
        /__w/tinygo/tinygo/interp/interpreter.go:560 +0x81f7
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc017d6c000, 0xc01660bc20, {0xc018d5ab10, 0x5, 0x0?}, 0xc007058330, {0xc019de5bd0, 0x10})
        /__w/tinygo/tinygo/interp/interpreter.go:560 +0x81f7
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc017d6c000, 0xc01660bbd0, {0xc016ab1c90, 0x5, 0x0?}, 0xc006c00ae0, {0xc01a1e26b0, 0xc})
        /__w/tinygo/tinygo/interp/interpreter.go:560 +0x81f7
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc017d6c000, 0xc01660bb80, {0xc016ab1a90, 0x5, 0x0?}, 0xc006bf12c0, {0xc01a122020, 0x8})
        /__w/tinygo/tinygo/interp/interpreter.go:560 +0x81f7
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc017d6c000, 0xc0168b3860, {0x0, 0x0, 0x1?}, 0x0, {0x6f5a3af, 0x4})
        /__w/tinygo/tinygo/interp/interpreter.go:560 +0x81f7
github.com/tinygo-org/tinygo/interp.Run({0x74c2db?}, 0x7f6d5b770830?, 0x0?)
        /__w/tinygo/tinygo/interp/interp.go:121 +0x725
github.com/tinygo-org/tinygo/builder.optimizeProgram({0x7f6d7ed001e0?}, 0xc00031a000)
        /__w/tinygo/tinygo/builder/build.go:1180 +0x32
github.com/tinygo-org/tinygo/builder.Build.func5(0xc016610ba0?)
        /__w/tinygo/tinygo/builder/build.go:611 +0x6ab
github.com/tinygo-org/tinygo/builder.runJob(0xc016610cc0, 0xc0062ab490)
        /__w/tinygo/tinygo/builder/jobs.go:212 +0x4d
created by github.com/tinygo-org/tinygo/builder.runJobs in goroutine 1
        /__w/tinygo/tinygo/builder/jobs.go:113 +0x5d8
```

**Comment by alixander** [comment]
@F0rgenet https://github.com/tinygo-org/tinygo/issues/4638
