### ISSUE TITLE
feature request: docusaurus plugin

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1448]

**Comment by soma-m** [comment]
Can't wait to get a Docusaurus plug-in 😊

**Comment by hapihacking** [comment]
ibid

**Comment by liuhailang** [comment]
Same here

**Comment by Airkro** [comment]
I created [remark-kroki](https://github.com/show-docs/remark-kroki) a few years ago to render many diagrams in Docusaurus.

It using [Kroki.io](https://kroki.io/) (an open-source online service) to render D2 diagrams. not the local d2 installation.

See: https://github.com/facebook/docusaurus/discussions/9608

A real-world example:

![image](https://github.com/terrastruct/d2/assets/12206891/d6178094-8379-4051-8b03-e15ed015a8d2)

**Comment by stereobooster** [comment]
Here is rehype plugin https://github.com/stereobooster/beoe/tree/main/packages/rehype-d2

```js
import rehypeD2 from "@beoe/rehype-d2";

export default {
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          path: 'docs',
          rehypePlugins: [rehypeD2],
        },
      },
    ],
  ],
};
```

Caveat: it requires local installation of D2. Which will work on your machine and in GitHub actions. No idea how to install D2 in Netlify or Vercel.

But this gone be solved when there will be [js package](https://github.com/terrastruct/d2/discussions/234#discussioncomment-11286029)

**Comment by hinorashi** [comment]
Should be awesome, let me try @Airkro and @stereobooster 's suggestions and feedback to u guys 👍🏻

**Comment by hinorashi** [comment]
@stereobooster
Here's what I do:
```sh
npm i @beoe/rehype-d2
```

In `docusaurus.config.js`:
```
          rehypePlugins: [
            [
              rehypeD2,
              {
                // Specify the path to the D2 CLI executable
                d2Path: "d2",
                // Specify the path to the D2 config file (optional)
                d2Config: "./d2.config.json",
                // Specify the output format (optional)
                outputFormat: "svg",
              },
            ],
          ],
```

I got this error:
```
> devops-wiki@0.0.0 start
> docusaurus start

[INFO] Starting the development server...

[ERROR] Error: Docusaurus could not load module at path "\xxx\docusaurus.config.js"
Cause: No "exports" main defined in \xxx\node_modules\@beoe\fenceparser\package.json
    at loadFreshModule (\xxx\node_modules\@docusaurus\utils\lib\moduleUtils.js:36:15)
    at loadSiteConfig (\xxx\node_modules\@docusaurus\core\lib\server\config.js:36:62)
    ... 7 lines matching cause stack trace ...
    at async file:///C:/Users/quannt/project/devops/devops-wiki/node_modules/@docusaurus/core/bin/docusaurus.mjs:44:3 {
  [cause]: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in \xxx\node_modules\@beoe\fenceparser\package.json
      at exportsNotFound (node:internal/modules/esm/resolve:304:10)
      at packageExportsResolve (node:internal/modules/esm/resolve:594:13)
      at resolveExports (node:internal/modules/cjs/loader:590:36)
      at Module._findPath (node:internal/modules/cjs/loader:667:31)
      at Module._resolveFilename (node:internal/modules/cjs/loader:1129:27)
      at Function.resolve (node:internal/modules/helpers:190:19)
      at _resolve (\xxx\node_modules\jiti\dist\jiti.js:1:246378)
      at jiti (\xxx\node_modules\jiti\dist\jiti.js:1:249092)
      at \xxx\node_modules\@beoe\rehype-code-hook-img\dist\utils.js:3:43
      at evalModule (\xxx\node_modules\jiti\dist\jiti.js:1:251913)
      at jiti (\xxx\node_modules\jiti\dist\jiti.js:1:249841)
      at \xxx\node_modules\@beoe\rehype-code-hook-img\dist\index.js:2:14
      at evalModule (\xxx\node_modules\jiti\dist\jiti.js:1:251913)
      at jiti (\xxx\node_modules\jiti\dist\jiti.js:1:249841)
      at \xxx\node_modules\@beoe\rehype-d2\dist\index.js:1:207
      at evalModule (\xxx\node_modules\jiti\dist\jiti.js:1:251913)
      at jiti (\xxx\node_modules\jiti\dist\jiti.js:1:249841)
      at \xxx\docusaurus.config.js:8:39
      at evalModule (\xxx\node_modules\jiti\dist\jiti.js:1:251913)
      at jiti (\xxx\node_modules\jiti\dist\jiti.js:1:249841)
      at loadFreshModule (\xxx\node_modules\@docusaurus\utils\lib\moduleUtils.js:33:16)
      at loadSiteConfig (\xxx\node_modules\@docusaurus\core\lib\server\config.js:36:62)
      at async Promise.all (index 1)
      at async loadContext (\xxx\node_modules\@docusaurus\core\lib\server\site.js:39:97)
      at async loadSite (\xxx\node_modules\@docusaurus\core\lib\server\site.js:143:21)
      at async createReloadableSite (\xxx\node_modules\@docusaurus\core\lib\commands\start\utils.js:49:16)
      at async Command.start (\xxx\node_modules\@docusaurus\core\lib\commands\start\start.js:22:28)
      at async Promise.all (index 0)
      at async runCLI (\xxx\node_modules\@docusaurus\core\lib\commands\cli.js:56:5)
      at async file:///C:/Users/quannt/project/devops/devops-wiki/node_modules/@docusaurus/core/bin/docusaurus.mjs:44:3 {
    code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
  }
}
[INFO] Docusaurus version: 3.7.0
Node version: v20.12.0
```

**Comment by stereobooster** [comment]
I can add exports field to `package.json` which would fix this error. I wonder though, where did you get those options? I feel like this comes from a different plugin

**Comment by mateothegreat** [comment]
> I can add exports field to `package.json` which would fix this error. I wonder though, where did you get those options? I feel like this comes from a different plugin
> 
> **UPD** ok it's not as simple as I though. beoe packages published as ESM. It seems that docusaurus uses old version of jiti which can't resolve exports. [facebook/docusaurus#10716](https://github.com/facebook/docusaurus/pull/10716). Not sure if it is fixable
> 
> **UPD**: I was able to resolve issues in `package.json`, but in the end I get this error:
> 
> ```
> ReferenceError [Error]: module is not defined in ES module scope
> This file is being treated as an ES module because it has a '.js' file extension and 'node_modules/.pnpm/@terrastruct+d2@0.1.23/node_modules/@terrastruct/d2/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
> ```

Ping me @stereobooster if you want to know what _exactly_ on https://github.com/terrastruct/d2/pull/2594 to help ya out 🤜
