### ISSUE TITLE
Example panics with v0.6.1 and later

### ISSUE THREAD

**Issue by jmooring** [terrastruct/d2#2258]
https://github.com/terrastruct/d2/blob/master/docs/examples/lib/1-d2lib/d2lib.go

This panics with v0.6.1 and later.

<details>
<summary>log</summary>

```text
2024-12-22T09:07:32-08:00 WARN  missing slog.Logger in context, see lib/log.With stack=goroutine 1 [running]:
runtime/debug.Stack()
        /snap/go/10748/src/runtime/debug/stack.go:26 +0x5e
oss.terrastruct.com/d2/lib/log.from({0x1518440, 0x1badf20})
        /home/jmooring/go/pkg/mod/oss.terrastruct.com/d2@v0.6.8/lib/log/log.go:23 +0x5f
oss.terrastruct.com/d2/lib/log.Debug({0x1518440, 0x1badf20}, {0xc54d93, 0xe}, {0xc00065fb58, 0x2, 0x2})
        /home/jmooring/go/pkg/mod/oss.terrastruct.com/d2@v0.6.8/lib/log/log.go:53 +0x3c
oss.terrastruct.com/d2/d2layouts.LayoutNested({0x1518440, 0x1badf20}, 0xc00048a0e0, {0x0?, {0x0?, 0x0?}}, 0x145e278, 0x145e2f8)
        /home/jmooring/go/pkg/mod/oss.terrastruct.com/d2@v0.6.8/d2layouts/d2layouts.go:264 +0x14e5
oss.terrastruct.com/d2/d2lib.compile({0x1518440, 0x1badf20}, 0xc00048a0e0, 0xc00065fe78, 0xc00065fee0)
        /home/jmooring/go/pkg/mod/oss.terrastruct.com/d2@v0.6.8/d2lib/d2.go:107 +0x11f
oss.terrastruct.com/d2/d2lib.Compile({0x1518440, 0x1badf20}, {0xc45ff2, 0x6}, 0xc0000061c0?, 0xc000006101?)
        /home/jmooring/go/pkg/mod/oss.terrastruct.com/d2@v0.6.8/d2lib/d2.go:78 +0x346
main.main()
        /home/jmooring/code/go-sandbox/cmd/d2/main.go:31 +0xdd

2024-12-22T09:07:32-08:00 WARN  missing slog.Logger in context, see lib/log.With stack=goroutine 1 [running]:
runtime/debug.Stack()
        /snap/go/10748/src/runtime/debug/stack.go:26 +0x5e
oss.terrastruct.com/d2/lib/log.from({0x1518440, 0x1badf20})
        /home/jmooring/go/pkg/mod/oss.terrastruct.com/d2@v0.6.8/lib/log/log.go:23 +0x5f
oss.terrastruct.com/d2/lib/log.Debug({0x1518440, 0x1badf20}, {0xc437d6, 0x4}, {0xc000c07b58, 0x2, 0x2})
        /home/jmooring/go/pkg/mod/oss.terrastruct.com/d2@v0.6.8/lib/log/log.go:53 +0x3c
oss.terrastruct.com/d2/d2layouts.LayoutNested({0x1518440, 0x1badf20}, 0xc00048a0e0, {0x0?, {0x0?, 0x0?}}, 0x145e278, 0x145e2f8)
        /home/jmooring/go/pkg/mod/oss.terrastruct.com/d2@v0.6.8/d2layouts/d2layouts.go:339 +0x1a65
oss.terrastruct.com/d2/d2lib.compile({0x1518440, 0x1badf20}, 0xc00048a0e0, 0xc000c07e78, 0xc000c07ee0)
        /home/jmooring/go/pkg/mod/oss.terrastruct.com/d2@v0.6.8/d2lib/d2.go:107 +0x11f
oss.terrastruct.com/d2/d2lib.Compile({0x1518440, 0x1badf20}, {0xc45ff2, 0x6}, 0xc0000061c0?, 0xc000006101?)
        /home/jmooring/go/pkg/mod/oss.terrastruct.com/d2@v0.6.8/d2lib/d2.go:78 +0x346
main.main()
        /home/jmooring/code/go-sandbox/cmd/d2/main.go:31 +0xdd
```
</details>
<br>

**Comment by alixander** [comment]
@jmooring These are just warnings, but still a good thing to fix, which I've done so here: https://github.com/terrastruct/d2/pull/2261
