### ISSUE TITLE
reproducible panic on sequence diagram (elk)

### ISSUE THREAD

**Issue by remlse** [terrastruct/d2#739]
Here's my diagram. It's not the final version of what I want it to be, I was in the middle of renaming stuff. But I think it should be a technically valid d2 diagram. The panic happens every time and immediately, for this specific diagram.

```
shape: sequence_diagram

user.shape: person
router: handlers (router)
handler: handlers (handler function)
db
models

HTTP request: {
  user -> router: sends request

  database transaction: {
    handlers -> db: |md
      fetches data from
      (e.g. GET request)
    |

    router -> models: |md
      calls business logic of
      (e.g. url schema validation)
    |

    router -> db: |md
      stores changed data in
      (e.g. POST request)
    |
  }

  router -> user: sends response
}
```

The exact command I used to render it:
```
d2 --watch --layout=elk --pad=32 docs/arc42/d2/backend_runtime_view.d2 docs/arc42/diagrams/backend_runtime_view.svg
```

My version of d2 (I installed with Go from source):
```
$ d2 --version
v0.1.4-HEAD
```

The panic backtrace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb9eae1]

goroutine 40 [running]:
oss.terrastruct.com/d2/d2layouts/d2sequence.getCenter(0x10?)
        /home/remo/.go/pkg/mod/oss.terrastruct.com/d2@v0.1.6/d2layouts/d2sequence/sequence_diagram.go:511 +0x21
oss.terrastruct.com/d2/d2layouts/d2sequence.getCenter(0x40f1e7?)
        /home/remo/.go/pkg/mod/oss.terrastruct.com/d2@v0.1.6/d2layouts/d2sequence/sequence_diagram.go:514 +0x8d
oss.terrastruct.com/d2/d2layouts/d2sequence.getCenter(0x40f1e7?)
        /home/remo/.go/pkg/mod/oss.terrastruct.com/d2@v0.1.6/d2layouts/d2sequence/sequence_diagram.go:514 +0x8d
oss.terrastruct.com/d2/d2layouts/d2sequence.getCenter(0x4d534db9bbe1467?)
        /home/remo/.go/pkg/mod/oss.terrastruct.com/d2@v0.1.6/d2layouts/d2sequence/sequence_diagram.go:514 +0x8d
oss.terrastruct.com/d2/d2layouts/d2sequence.(*sequenceDiagram).routeMessages(0xc0004000e0)
        /home/remo/.go/pkg/mod/oss.terrastruct.com/d2@v0.1.6/d2layouts/d2sequence/sequence_diagram.go:460 +0xe5
oss.terrastruct.com/d2/d2layouts/d2sequence.(*sequenceDiagram).layout(0xc000146380?)
        /home/remo/.go/pkg/mod/oss.terrastruct.com/d2@v0.1.6/d2layouts/d2sequence/sequence_diagram.go:188 +0x32
oss.terrastruct.com/d2/d2layouts/d2sequence.layoutSequenceDiagram(0xc000146240, 0xc0000d6f00)
        /home/remo/.go/pkg/mod/oss.terrastruct.com/d2@v0.1.6/d2layouts/d2sequence/layout.go:109 +0x292
oss.terrastruct.com/d2/d2layouts/d2sequence.WithoutSequenceDiagrams({0xc000268240?, 0xc000146500?}, 0xc000146240)
        /home/remo/.go/pkg/mod/oss.terrastruct.com/d2@v0.1.6/d2layouts/d2sequence/layout.go:34 +0x385
oss.terrastruct.com/d2/d2layouts/d2sequence.Layout({0x19e0fb8, 0xc0006fd340}, 0xc000146240, 0xc0005a80a8)
        /home/remo/.go/pkg/mod/oss.terrastruct.com/d2@v0.1.6/d2layouts/d2sequence/layout.go:81 +0x31
oss.terrastruct.com/d2/d2lib.Compile({0x19e0fb8, 0xc0006fd340}, {0xc000136600, 0x1ee}, 0x2?)
        /home/remo/.go/pkg/mod/oss.terrastruct.com/d2@v0.1.6/d2lib/d2.go:60 +0x196
main.compile({0x19e0fb8, 0xc0006fd340}, 0x7fbc0c001001?, {0x19e2bc0, 0x21b5ce8}, 0x0, 0x20, 0x0, {0x7ffc5ff6864e, 0x25}, ...)
        /home/remo/.go/pkg/mod/oss.terrastruct.com/d2@v0.1.6/main.go:243 +0x1bc
main.(*watcher).compileLoop(0xc0002ba160, {0x19e0fb8, 0xc0006fd340})
        /home/remo/.go/pkg/mod/oss.terrastruct.com/d2@v0.1.6/watch.go:359 +0x405
main.(*watcher).goFunc.func1()
        /home/remo/.go/pkg/mod/oss.terrastruct.com/d2@v0.1.6/watch.go:193 +0x76
created by main.(*watcher).goFunc
        /home/remo/.go/pkg/mod/oss.terrastruct.com/d2@v0.1.6/watch.go:189 +0x8d
```

**Comment by jamestiotio** [comment]
Hi @remlse, it seems that you had a small typo.

Under `database transaction`, it should be `handler -> db` instead of `handlers -> db`. Implementing said modification would render a proper diagram:

![Sequence Diagram](https://user-images.githubusercontent.com/18364745/216801533-7bcb44ae-5e40-400b-92f5-792986722bde.svg)

**Comment by remlse** [comment]
Yes, that's right. I was in the middle of renaming that thing.

I can totally understand that there are some limitations to the implicit object creation that usually happens when accessing a property of something that doesn't exist yet.

The problem is more that d2 crashes outright. Running it with `--watch`, the user would expect it to keep running, even when the diagram is in a temporarily invalid state. Showing some error, refusing to rerender the invalid diagram are totally fine, but I think it should recover once the diagram is in a valid state again.

**Comment by alixander** [comment]
We're making sequence diagrams more robust for this next release (rewrote a bunch of the compiler). Apologies for this confusing experience, and totally right -- we should be recovering panics. I'll keep this issue open to track that.

**Comment by remlse** [comment]
No problem! Thank you for your time. I will unsubscribe myself from this issue if you're keeping open for longer.
